# Generated by Django 3.1 on 2020-10-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=150)),
                ('address2', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
