# Generated by Django 3.1.5 on 2021-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
