# Generated by Django 3.1.5 on 2021-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
